### ISSUE TITLE
Request and some inconsistencies 

### ISSUE THREAD

**Issue by NeuronSooup** [Fausto-Korpsvart/Tokyo-Night-GTK-Theme#1]
What a lovely theme you got there! Im probably gonna stick with this in years to come
There is something I would like to request if you got the time to change it 
First some minor inconsistencies
Overlapping in some layouts: 
https://ibb.co/dP8dtsb
https://ibb.co/zr4xF5m
Spacing in this picture is too tight for me:
https://ibb.co/T8WD1sd
Request: I think some UI element such as these should not have that big of a title bar that takes up screen real-estate 
https://ibb.co/rc3rD8v
Especially the terminal: https://ibb.co/8KVJHnT

**Comment by Fausto-Korpsvart** [comment]
Greetings, NeuronSooup.
I will work on the details you mention, in fact I'm already working on some bugs that appear in the Zorin distro, now I will take into account what you report to add to my to-do list.
Thank you for reporting these inconsistencies, as soon as I complete the changes I will upload the update. 
Thank you again }

**Comment by NeuronSooup** [comment]
Glad to help
