### ISSUE TITLE
Dark theme hiding icons

### ISSUE THREAD

**Issue by vinilopes91** [Fausto-Korpsvart/Tokyo-Night-GTK-Theme#13]
Both dark themes are hiding icons
![123](https://user-images.githubusercontent.com/51728145/176534294-686c2774-e901-4b27-816c-3e7ad9906410.png)

**Comment by vinilopes91** [comment]
I'm using Ubuntu 20.04, the light theme appears the icons but both Dark-B and Dark-BL these icons are not showing. I tested other icon options like TokyoNight and the system ones and the problem remained. Is any additional installation required?

Light theme:
![2022-06-30_15-53](https://user-images.githubusercontent.com/51728145/176755893-d5c39cd4-3451-4d18-8d00-d11dfc131017.png)

**Comment by Fausto-Korpsvart** [comment]
> Thanks for the support @Fausto-Korpsvart
> 
> I'm using Ubuntu 20.04, the light theme appears the icons but both Dark-B and Dark-BL these icons are not showing. I tested other icon options like TokyoNight and the system ones and the problem remained. Is any additional installation required?
> 
> Light theme: ![2022-06-30_15-53](https://user-images.githubusercontent.com/51728145/176755893-d5c39cd4-3451-4d18-8d00-d11dfc131017.png)

@vinilopes91, I haven't tested on Ubuntu yet, I will check and see what the problem is to give a solution as soon as possible, again, thanks for reporting the bug and for the support. };-]

**Comment by vinilopes91** [comment]
Update: I upgraded to the latest version of ubuntu (22.04) and the problem is fixed. 🎉

![Screenshot from 2022-07-01 15-53-02](https://user-images.githubusercontent.com/51728145/176954135-7e85594b-3ece-42ef-b1b6-bbe10b130908.png)

**Comment by Fausto-Korpsvart** [comment]
> Update: I upgraded to the latest version of ubuntu (22.04) and the problem is fixed. tada
> 
> ![Screenshot from 2022-07-01 15-53-02](https://user-images.githubusercontent.com/51728145/176954135-7e85594b-3ece-42ef-b1b6-bbe10b130908.png)

Sorry, @vinilopes91, I didn't realize you were on version 20.04 }:D, you typed Ubuntu and I automatically thought you were on the latest version and tried version 22.04, anyway I'm going to install version 20.04 to look for the source of the problem, but it's working on the latest Gnome version makes me think it's incompatibility with versions prior to Gnome 42.

Good that the theme is already working fine, again, thanks for reporting bugs and for the support };-]
