### ISSUE TITLE
I put gtk.css (BL version) (from the gnome 42 folder) into the gtk 4.0 folder, but nothing is hapenning at all, no color changes even after rebooting!

### ISSUE THREAD

**Issue by 0Aredjay0** [Fausto-Korpsvart/Tokyo-Night-GTK-Theme#14]

**Comment by Fausto-Korpsvart** [comment]
What distribution are you using, I'm on Fedora, and I've tested on Manjaro, Ubuntu and OpenSUSE and I haven't had any problems so far.
The GTK4 path to use is '~/.config/gtk-4.0/', if you have used that path, I find it strange that it doesn't work.
