### ISSUE TITLE
Dark theme for dash to dock users

### ISSUE THREAD

**Issue by CodeKid0** [Fausto-Korpsvart/Tokyo-Night-GTK-Theme#16]
Hello, could You maybe provide a dark version of the theme for dash to dock users? @Fausto-Korpsvart

**Comment by Fausto-Korpsvart** [comment]
> Hello, could You maybe provide a dark version of the theme for dash to dock users? @Fausto-Korpsvart

I thought I had already changed that, could you take a screenshot?
I am using 'Fedora 36' with the 'Dash to Dock for COSMIC' extension and the theme is dark, even without using the extension the theme is dark.
What versions of GNOME and Dash to Dock are you using?

A screenshot of the Tokyonight theme.
![Tokyonight-DTD](https://user-images.githubusercontent.com/47998118/184143146-9b83478d-7262-4fe0-86c5-f11ff12f0126.png)

**Comment by CodeKid0** [comment]
For some reason the theme didn't work but now it does? Weird.

**Comment by Fausto-Korpsvart** [comment]
> For some reason the theme didn't work but now it does? Weird.

Yes, it's weird, but it's great that it's already working.
