### ISSUE TITLE
dock has too much space at the top

### ISSUE THREAD

**Issue by furkan161** [Fausto-Korpsvart/Tokyo-Night-GTK-Theme#19]
hello the dock has too much space at the top.
![Screenshot from 2022-08-31 03-49-02](https://user-images.githubusercontent.com/81360830/187568972-bb7cc4b6-4997-4b7c-bac8-165cac574b3b.png)

**Comment by Fausto-Korpsvart** [comment]
> hello the dock has too much space at the top. ![Screenshot from 2022-08-31 03-49-02](https://user-images.githubusercontent.com/81360830/187568972-bb7cc4b6-4997-4b7c-bac8-165cac574b3b.png)

That's quite strange, I've been testing and nothing like that happens on my desktop with the same theme. 
What distro are you using and what version of GNOME?

**Comment by furkan161** [comment]
> > hello the dock has too much space at the top. ![Screenshot from 2022-08-31 03-49-02](https://user-images.githubusercontent.com/81360830/187568972-bb7cc4b6-4997-4b7c-bac8-165cac574b3b.png)
> 
> That's quite strange, I've been testing and nothing like that happens on my desktop with the same theme. What distro are you using and what version of GNOME?
problem solved after installing dash to dock and rebooting but no idea with one solved the problem maybe both.
![Screenshot from 2022-09-01 00-28-18](https://user-images.githubusercontent.com/81360830/187788382-82a4f207-71cc-42aa-a338-b7891c440090.png)

**Comment by Fausto-Korpsvart** [comment]
> > > hello the dock has too much space at the top. ![Screenshot from 2022-08-31 03-49-02](https://user-images.githubusercontent.com/81360830/187568972-bb7cc4b6-4997-4b7c-bac8-165cac574b3b.png)
> > 
> > 
> > That's quite strange, I've been testing and nothing like that happens on my desktop with the same theme. What distro are you using and what version of GNOME?
> 
> problem solved after installing dash to dock and rebooting but no idea which one solved the problem maybe both. ![Screenshot from 2022-09-01 00-28-18](https://user-images.githubusercontent.com/81360830/187788382-82a4f207-71cc-42aa-a338-b7891c440090.png)

When installing Dash To Dock it takes the extension settings and that may fix the error, but the strange thing is that I've tested on Fedora and Manjaro and there are no errors, I think it's Ubuntu theme settings error.

Thanks for reporting the error, I'll keep looking for the root of the problem to fix it.

**Comment by furkan161** [comment]
> > > > hello the dock has too much space at the top. ![Screenshot from 2022-08-31 03-49-02](https://user-images.githubusercontent.com/81360830/187568972-bb7cc4b6-4997-4b7c-bac8-165cac574b3b.png)
> > > 
> > > 
> > > That's quite strange, I've been testing and nothing like that happens on my desktop with the same theme. What distro are you using and what version of GNOME?
> > 
> > 
> > problem solved after installing dash to dock and rebooting but no idea which one solved the problem maybe both. ![Screenshot from 2022-09-01 00-28-18](https://user-images.githubusercontent.com/81360830/187788382-82a4f207-71cc-42aa-a338-b7891c440090.png)
> 
> When installing Dash To Dock it takes the extension settings and that may fix the error, but the strange thing is that I've tested on Fedora and Manjaro and there are no errors, I think it's Ubuntu theme settings error.
> 
> Thanks for reporting the bug, I'll keep looking for the source of the problem to fix it.


There is also this happening sometimes but rebooting it fixes probably related to this issue.
![Screenshot from 2022-09-01 01-41-43](https://user-images.githubusercontent.com/81360830/187797675-0c627fcb-fd40-45f0-a0cc-fbcd5fec7c95.png)
