### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by niels0n** [Fausto-Korpsvart/Tokyo-Night-GTK-Theme#2]
This is so cool!
Only problem is that it adds a box around dash to panel like it does in the shell (see screenshot attached, dash to panel is the one at the bottom), but I really don't like it. Would it be possible to remove it?
![Screenshot from 2022-01-22 02-41-19](https://user-images.githubusercontent.com/47432766/150619797-6d2ea586-e5d1-43f3-8d4e-da2f66df250e.png)

**Comment by DevSallSa** [comment]
Hi @niels0n,
Just a question out of context.
Am using Pop_OS! too. How did you manage to add these icons on the left corner of the top bar ?

**Comment by Fausto-Korpsvart** [comment]
> This is so cool! Only problem is that it adds a box around dash to panel like it does in the shell (see screenshot attached, dash to panel is the one at the bottom), but I really don't like it. Would it be possible to remove it? ![Screenshot from 2022-01-22 02-41-19](https://user-images.githubusercontent.com/47432766/150619797-6d2ea586-e5d1-43f3-8d4e-da2f66df250e.png)

I understand, I really didn't know that it looks like this in Dash to Panel, I started this theme for personal use and I don't use Dash to Panel, I've always used the top panel and Dash to Dock so I made it for the Dock, but soon I will upload a version of the Shell adapted for Dash to panel.

**Comment by Fausto-Korpsvart** [comment]
> Hi @niels0n, Just a question out of context. Am using Pop_OS! too. How did you manage to add these icons on the left corner of the top bar ?

I think it is the extension 'BarBar Task Bar'

**Comment by niels0n** [comment]
> Hi @niels0n, Just a question out of context. Am using Pop_OS! too. How did you manage to add these icons on the left corner of the top bar ?

hi! actually it is [workspace bar](https://extensions.gnome.org/extension/3851/workspaces-bar/) extension with nerd font icons as workspaces names done using dconf editor.

**Comment by niels0n** [comment]
> > This is so cool! Only problem is that it adds a box around dash to panel like it does in the shell (see screenshot attached, dash to panel is the one at the bottom), but I really don't like it. Would it be possible to remove it? ![Screenshot from 2022-01-22 02-41-19](https://user-images.githubusercontent.com/47432766/150619797-6d2ea586-e5d1-43f3-8d4e-da2f66df250e.png)
> 
> I understand, I really didn't know that it looks like this in Dash to Panel, I started this theme for personal use and I don't use Dash to Panel, I've always used the top panel and Dash to Dock so I made it for the Dock, but soon I will upload a version of the Shell adapted for Dash to panel.

okay thank you so much! i was hoping for a simple workaround, like remove a character in the .css or something lol
i'll wait for the new version then.

**Comment by DevSallSa** [comment]
> hi! actually it is workspace bar extension with nerd font icons as workspaces names done using dconf editor.

Thanks !

**Comment by Fausto-Korpsvart** [comment]
> This is so cool! Only problem is that it adds a box around dash to panel like it does in the shell (see screenshot attached, dash to panel is the one at the bottom), but I really don't like it. Would it be possible to remove it? ![Screenshot from 2022-01-22 02-41-19](https://user-images.githubusercontent.com/47432766/150619797-6d2ea586-e5d1-43f3-8d4e-da2f66df250e.png)

Updated theme in Gnome Look.

**Comment by niels0n** [comment]
> > This is so cool! Only problem is that it adds a box around dash to panel like it does in the shell (see screenshot attached, dash to panel is the one at the bottom), but I really don't like it. Would it be possible to remove it? ![Screenshot from 2022-01-22 02-41-19](https://user-images.githubusercontent.com/47432766/150619797-6d2ea586-e5d1-43f3-8d4e-da2f66df250e.png)
> 
> Updated theme in Gnome Look.

thank you! i really appreciate it. unfortunately though, nothing changes, as you can see in the screenshot. i deleted the old tokyonight folders and reinstalled it selecting the new theme. how can i apply the new version?
![Screenshot from 2022-02-02 00-05-00](https://user-images.githubusercontent.com/47432766/152067368-976ac27d-7553-42c2-90b7-8deea203e68a.png)

**Comment by Fausto-Korpsvart** [comment]
> > > This is so cool! Only problem is that it adds a box around dash to panel like it does in the shell (see screenshot attached, dash to panel is the one at the bottom), but I really don't like it. Would it be possible to remove it? ![Screenshot from 2022-01-22 02-41-19](https://user-images.githubusercontent.com/47432766/150619797-6d2ea586-e5d1-43f3-8d4e-da2f66df250e.png)
> > 
> > 
> > Updated theme in Gnome Look.
> 
> thank you! i really appreciate it. unfortunately though, nothing changes, as you can see in the screenshot. i deleted the old tokyonight folders and reinstalled it selecting the new theme. how can i apply the new version? ![Screenshot from 2022-02-02 00-05-00](https://user-images.githubusercontent.com/47432766/152067368-976ac27d-7553-42c2-90b7-8deea203e68a.png)

Sorry for not clarifying, the Gnome Shell theme is separate, you must replace the 'gnome-shell' folder which is inside the theme folder.
Here's the link to the version you need: ![Gnome Shell](https://www.pling.com/s/Gnome/p/1681470)

**Comment by niels0n** [comment]
> > > > This is so cool! Only problem is that it adds a box around dash to panel like it does in the shell (see screenshot attached, dash to panel is the one at the bottom), but I really don't like it. Would it be possible to remove it? ![Screenshot from 2022-01-22 02-41-19](https://user-images.githubusercontent.com/47432766/150619797-6d2ea586-e5d1-43f3-8d4e-da2f66df250e.png)
> > > 
> > > 
> > > Updated theme in Gnome Look.
> > 
> > 
> > thank you! i really appreciate it. unfortunately though, nothing changes, as you can see in the screenshot. i deleted the old tokyonight folders and reinstalled it selecting the new theme. how can i apply the new version? ![Screenshot from 2022-02-02 00-05-00](https://user-images.githubusercontent.com/47432766/152067368-976ac27d-7553-42c2-90b7-8deea203e68a.png)
> 
> Sorry for not clarifying, the Gnome Shell theme is separate, you must replace the 'gnome-shell' folder which is inside the theme folder. Here's the link to the version you need: [**Tokyo Night Shell Themes**](https://www.pling.com/p/1681470/)

did the trick! thank you so much.
