### ISSUE TITLE
gnome-shell theme probable wrong color

### ISSUE THREAD

**Issue by Vahelnir** [Fausto-Korpsvart/Tokyo-Night-GTK-Theme#20]
Hello,
I noticed that the `gnome-shell` part of the theme is using the blueish `#0db9d7` color instead of the light grey `#c0caf5`. 
Is that wanted ?
![Default](https://user-images.githubusercontent.com/9640068/193555292-732c1a45-f5cb-4546-9366-7221d0de2d4b.png)
 
 I would have expected it to look like 
![Screenshot from 2022-10-03 12-24-27](https://user-images.githubusercontent.com/9640068/193555651-c2243ce3-e775-443c-84a6-45fcd5a157bb.png)

I am using the Storm Borderless variant, but I guess it must be the same in the others. 
I wanted to ask before opening a PR.

Edit: On the second screenshot, the purple should be this blue `#0db9d7`.

**Comment by Vahelnir** [comment]
> It's not the wrong colour, that's the new colour I've put for the borderless version;

Oh sorry, I did not notice. My bad.

> The next update I might add a version of Gnome Shell with white text for those who don't like the Cyan colour.

I would like that, though I imagine maintaining all those different themes might be annoying. 

Thanks for your work !

**Comment by Fausto-Korpsvart** [comment]
> > It's not the wrong colour, that's the new colour I've put for the borderless version;
> 
> Oh sorry, I did not notice. My bad.
> 
> > The next update I might add a version of Gnome Shell with white text for those who don't like the Cyan colour.
> 
> I would like that, though I imagine maintaining all those different themes might be annoying.
> 
> Thanks for your work !

It's not annoying, and it's really great that there are more options for everyone who uses the themes; so in the next update I will put a version with white text.

Thanks for your support!

**Comment by Fausto-Korpsvart** [comment]
> > It's not the wrong colour, that's the new colour I've put for the borderless version;
> 
> Oh sorry, I did not notice. My bad.
> 
> > The next update I might add a version of Gnome Shell with white text for those who don't like the Cyan colour.
> 
> I would like that, though I imagine maintaining all those different themes might be annoying.
> 
> Thanks for your work !

I have updated the theme and put both versions, White and Cyan font for the top panel of Gnome Shell.
[Gnome Shell Themes](https://www.pling.com/s/Gnome/p/1681470)
