### ISSUE TITLE
Firefox theme windows corner issue ?

### ISSUE THREAD

**Issue by bbrx94** [Fausto-Korpsvart/Tokyo-Night-GTK-Theme#22]
Hello,

It's to make a Firefox theme (like Whitesur theme) ?
How can I fix this problem

![image](https://user-images.githubusercontent.com/107874456/196463971-69236e14-4be9-440c-8771-c4e21eb90c73.png)

Best regards,

**Comment by Fausto-Korpsvart** [comment]
> bbrx94

Greetings, @bbrx94 

What distro are you using?
I'm on Fedora 36 and I don't have that problem, in the distro I've tried I haven't seen that error, the distros are Manjaro, OpensSUSE, PopOS and some others with Gnome by default. And no, I'm not making a Firefox theme like WhiteSur.

![Firefox](https://user-images.githubusercontent.com/47998118/196538062-0f0089fc-6d6a-46aa-a8a6-6dc163c29199.png)
Here is a screenshot of Firefox on Fedora.

**Comment by bbrx94** [comment]
Oh, ok, I'm using Arch Linux, please get info.
![image](https://user-images.githubusercontent.com/107874456/196548821-8a8ecf07-29a0-468e-a6d0-ab503e170422.png)

**Comment by bbrx94** [comment]
Greetings,

I also tried to reset Firefox settings to see, from "Help" -> "Fix Firefox" and same problem.
I have the issue with libreWolf too (based on Firefox)

Best regards,
B.

**Comment by Fausto-Korpsvart** [comment]
> Greetings,
> 
> I also tried to reset Firefox settings to see, from "Help" -> "Fix Firefox" and same problem. I have the issue with libreWolf too (based on Firefox)
> 
> Best regards, B.

Alright, I don't think it's a problem with the Firefox or LibreWolf settings, it's obviously a problem with the theme; I'm going to check what's going on with this error because I haven't had this problem before.
I will check and make an update when I find the error.

Thanks for reporting and for the support. };-]

**Comment by bbrx94** [comment]
OK thanks, also how I can get a same position of buttons? what I need to change in css and which files?
![image](https://user-images.githubusercontent.com/107874456/196660017-40d5f364-bbb7-44d7-b389-4efe11277b8e.png)

**Comment by Fausto-Korpsvart** [comment]
> OK thanks, also how I can get a same position of buttons on left side? what I need to change in css and which files? In this capture, you have Nautilus / Gedit / VS Code (at bottom) ![image](https://user-images.githubusercontent.com/107874456/196660017-40d5f364-bbb7-44d7-b389-4efe11277b8e.png)
> 
> If I put buttons at right, no problem, it's strange? ![image](https://user-images.githubusercontent.com/107874456/196666643-549e333f-5c0b-4977-83b8-47393170f172.png)

I can add the padding when the icons are on the right side to be the same as when they are on the left side, but this affects only native GNOME applications, I have to do some research to know how to apply this padding to applications that are not written in GTK, because I guess that's why VSCode doesn't apply this padding, I don't use the native VSCode window, actually I almost don't use VSCode, so I didn't notice it, but I have noticed it in other applications, in the next update I will try to solve this problem with non-native applications, but you will see the change in the native GNOME applications.

**Comment by bbrx94** [comment]
Great, thanks.
For Evolution (native GTK) and Firefox is a same than VS Code

**Comment by Fausto-Korpsvart** [comment]
> Great, thanks. For Evolution (is not native GTK?) and Firefox is a same than VS Code
> 
> ![image](https://user-images.githubusercontent.com/107874456/196742155-12d5c6b1-a265-4054-988d-8fb115ac3f34.png)
Which version of Evolution are you using? Because I just installed it and it works fine for me, it respects the theme.
![evolution](https://user-images.githubusercontent.com/47998118/196823233-2e944262-0882-4938-98d3-ff195b3fadec.png)

**Comment by bbrx94** [comment]
Greetings,

Yes, it's a same version.
![image](https://user-images.githubusercontent.com/107874456/196875372-a119756f-6907-4c4c-95ef-e20c7250168e.png)

I saw some theme require this : sudo pacman -S gtk-engine-murrine gtk-engines (I tried and no change for me).

Regards,
B.

**Comment by bbrx94** [comment]
For Firefox, I tried to adapt Whitesur and for the moment I don't change icons yet 

![image](https://user-images.githubusercontent.com/107874456/196876229-17fb44cb-97be-4805-8b18-c3544d4a27cc.png)

So currently I'm in this configuration

![image](https://user-images.githubusercontent.com/107874456/196875999-06d0db32-a367-4e14-b35b-1fda872cceeb.png)

**Comment by Fausto-Korpsvart** [comment]
> For Firefox, I tried to adapt Whitesur and for the moment I don't change icons yet
> 
> ![image](https://user-images.githubusercontent.com/107874456/196876229-17fb44cb-97be-4805-8b18-c3544d4a27cc.png)
> 
> So currently I'm in this configuration
> 
> ![image](https://user-images.githubusercontent.com/107874456/196875999-06d0db32-a367-4e14-b35b-1fda872cceeb.png)

I have updated to fix the position of the window control buttons and the title bar, it seems that it is not what I thought, as you can apply styles to the Headerbar and the Titlebar, now it is a bit more similar to the native GTK applications.

Unfortunately, I haven't been able to reproduce the Firefox problem yet, but I'm still looking for a solution for the rounded corners, when I find it I'll update again.

And thanks for reminding me about the `gtk-engine-murrine and gtk-engines` dependencies, I will put in the description that it is necessary to install these packages to avoid some problems.

Again, thanks for your support and for reporting bugs to make the theme look better.

**Comment by bbrx94** [comment]
Thanks you, nice job!

**Comment by XMelph** [comment]
I'm currently facing the same issue on Fedora 36. I still don't understand exactly why, as before the theme worked fine on this distro.

**Comment by Fausto-Korpsvart** [comment]
> I'm currently facing the same issue on Fedora 36. I still don't understand exactly why, as before the theme worked fine on this distro.

I still don't understand the origin of this error, in my tests with virtual machines I don't have this problem, I have reinstalled the virtual machines to have the latest versions and even in Fedora 37 I don't have this problem in Firefox; I am using Fedora 36 as my main system and Firefox applies the themes well.

I will continue to investigate where this error comes from to fix it as soon as possible, thanks for reporting it.

**Comment by bbrx94** [comment]
Hello,

I have news about Firefox problem FF menu round corner on Arch Linux (Wayland / Gnome), get a look here please ;)
https://bbs.archlinux.org/viewtopic.php?id=280099

**Comment by Fausto-Korpsvart** [comment]
> Hello,
> 
> I have news about Firefox problem FF menu round corner on Arch Linux (Wayland / Gnome), get a look here please ;) https://bbs.archlinux.org/viewtopic.php?id=280099

Interesting, I need to check this out in detail to see how to apply this.
Thanks for taking the time to do the research and for sharing the information, it is very useful.

**Comment by rafay99-epic** [comment]
> I'm currently facing the same issue on Fedora 36. I still don't understand exactly why, as before the theme worked fine on this distro.

Brother I am using Firefox with Fedora 38, and I did not see this issue, but it is interesting.

**Comment by wsouto** [comment]
> Brother I am using Firefox with Fedora 38, and I did not see this issue, but it is interesting.

That's odd. I'm on 38 too, and having this issue so that it might not be just the theme.
This is the only theme I have ever used in GNOME, so I like seeing this bug squashed.

**Comment by wsouto** [comment]
The thing is that I'm using Firefox Developer Edition (currently version 114.0b9) and the corners are buggy, but on default Firefox (113.0.1) it's showing as expected, so it's not the theme.

Thanks for making a great theme!
