### ISSUE TITLE
weird border color, readme not updated?

### ISSUE THREAD

**Issue by sebbonit** [Fausto-Korpsvart/Tokyo-Night-GTK-Theme#23]
![image](https://user-images.githubusercontent.com/36650750/199649211-915aa414-8b77-41f8-a63a-6c6c5f70579a.png)
 
Weird border color, not at all similar to the screenshoots in the readme.

**Comment by Fausto-Korpsvart** [comment]
> ![image](https://user-images.githubusercontent.com/36650750/199649211-915aa414-8b77-41f8-a63a-6c6c5f70579a.png)
> 
> Weird border color, not at all similar to the screenshoots in the readme.

I have not yet updated the screenshot, I will do so soon.
