### ISSUE TITLE
gtk2 theme broken

### ISSUE THREAD

**Issue by Nikoof** [Fausto-Korpsvart/Tokyo-Night-GTK-Theme#24]
The gtk2 theme appears to be broken for some reason.
![tokyonight-gtk2-lxappearance](https://user-images.githubusercontent.com/70487229/200360613-734858f5-5550-43ae-9298-577f3e8b519b.png)
![tokyonight-gtk2-gimp](https://user-images.githubusercontent.com/70487229/200360632-ab6e50e3-812a-481f-b06f-7d7f055015d4.png)

I'm really not sure what might be causing this. I've taken a look at the gtkrc file in the Tokyonight-Dark-B/gtk-2.0 folder and i've noticed that the background/foreground colors are inverted there, but changing them around doesn't seem to yield a working theme. I don't really know my way around gtk theming so I don't know where else to look.

I've been using this theme for about 5 months now and it was working for both of the aforementioned apps, but I've recently distrohopped and I downloaded the latest version from gnome-look.org, which is affected by this. I can't figure out which update changed this.

I'm currently using Arch Linux should that be relevant. Many thanks!

**Comment by Fausto-Korpsvart** [comment]
> The gtk2 theme appears to be broken for some reason. ![tokyonight-gtk2-lxappearance](https://user-images.githubusercontent.com/70487229/200360613-734858f5-5550-43ae-9298-577f3e8b519b.png) ![tokyonight-gtk2-gimp](https://user-images.githubusercontent.com/70487229/200360632-ab6e50e3-812a-481f-b06f-7d7f055015d4.png)
> 
> I'm really not sure what might be causing this. I've taken a look at the gtkrc file in the Tokyonight-Dark-B/gtk-2.0 folder and i've noticed that the background/foreground colors are inverted there, but changing them around doesn't seem to yield a working theme. I don't really know my way around gtk theming so I don't know where else to look.
> 
> I've been using this theme for about 5 months now and it was working for both of the aforementioned apps, but I've recently distrohopped and I downloaded the latest version from gnome-look.org, which is affected by this. I can't figure out which update changed this.
> 
> I'm currently using Arch Linux should that be relevant. Many thanks!

This is strange, as I haven't touched anything in the GTK2 file, and I'm trying with GIMP and I don't see any problem.
Are you using GNOME and which version? Or are you using some TWM?

Either way, thanks for reporting the bug, this week I hope to update the theme, I'm working on it. }:-]

**Comment by Nikoof** [comment]
I'm using LeftWM, so I doubt that's interfering with it, though I've managed to replicate the problem on GNOME 43 on a separate machine.

If I manage to figure out the problem I'll update you. Thanks for the quick response. Great theme and keep up the good work!

**Comment by Fausto-Korpsvart** [comment]
> I'm using LeftWM, so I doubt that's interfering with it, though I've managed to replicate the problem on GNOME 43 on a separate machine.
> 
> If I manage to figure out the problem I'll update you. Thanks for the quick response. Great theme and keep up the good work!

I'm on Fedora 37 with Gnome 43, GIMP 2.10.32, and I can't reproduce the problem.
I'm using the same files that I uploaded to Pling and that are currently in this repository, but I can't replicate the problem.

Here is a screenshot of GIMP.
![GIMP](https://user-images.githubusercontent.com/47998118/200372431-0fefef2c-44a9-4361-88d2-83730c553b60.png)

**Comment by Nikoof** [comment]
Oh. I think GIMP comes with its own theme. You can make it use the system theme via Edit > Preferences > Interface > Theme > System. I probably should have mentioned that before - oops.

![image](https://user-images.githubusercontent.com/70487229/200375137-765545ba-0eba-4eea-968b-4570ae4796af.png)

This affects all gtk2 applications as far as I can see, so you could try replicating it with something like pcmanfm or lxappearance - pretty much anything gtk2.

**Comment by Fausto-Korpsvart** [comment]
> Oh. I think GIMP comes with its own theme. You can make it use the system theme via Edit > Preferences > Interface > Theme > System. I probably should have mentioned that before - oops.
> 
> ![image](https://user-images.githubusercontent.com/70487229/200375137-765545ba-0eba-4eea-968b-4570ae4796af.png)
> 
> This affects all gtk2 applications as far as I can see, so you could try replicating it with something like pcmanfm or lxappearance - pretty much anything gtk2.

You're right, I also forgot that GIMP has themes in the preferences, I'm going to check the theme to find the source of the problem and fix it before the update I plan to do this week.

**Comment by Nikoof** [comment]
Awesome! Appreciate the support and looking forward to the update 👍.

**Comment by Fausto-Korpsvart** [comment]
> Awesome! Appreciate the support and looking forward to the update +1.

I found the error, the problem is the colour `#c0caf5`, you can change it to `#e1e2e7` for the moment to fix the error, at least until I make the update.

Here is a screenshot of the bug fixed.
![GTK2-FIXED](https://user-images.githubusercontent.com/47998118/200397344-0cb38b8d-a021-4035-ac1b-86bd20f5bae5.png)

**Comment by Nikoof** [comment]
Interesting. Does this also fix the dark themes? Because the light theme works fine for me; only the dark, storm and moon themes are broken. The first few screenshots are of the Tokyonight-Dark-B theme.

**Comment by Fausto-Korpsvart** [comment]
> Interesting. Does this also fix the dark themes? Because the light theme works fine for me; only the dark, storm and moon themes are broken. The first few screenshots are of the Tokyonight-Dark-B theme.

You mean you have the same error in the Storm and Moon versions?
If so, just make the same colour change in the GTK2 files corresponding to each dark version.
I have already fixed it in the Storm and Moon versions too, I just need to make all the necessary changes, and I'll do the update during the week.

Thanks for reporting the bug and for your support. }:-]
