### ISSUE TITLE
GNOME 43 support

### ISSUE THREAD

**Issue by Raiden0456** [Fausto-Korpsvart/Tokyo-Night-GTK-Theme#25]
Hey! Just wanted to know when gnome 43 update will arrive.
Cheers!)

**Comment by Fausto-Korpsvart** [comment]
> Hey! Just wanted to know when gnome 43 update will arrive. Cheers!)

I'm just finishing some details for the Tokyonight Storm version, so when everything is ready I'll do the update this day.
