### ISSUE TITLE
Broken GTK2 part of the theme.

### ISSUE THREAD

**Issue by Grumpoo** [Fausto-Korpsvart/Tokyo-Night-GTK-Theme#26]
Hello!

When downloading your theme to match my rice, I have noticed that the theme was broken in apps like LXAppearance and PCManFM as seen [here](https://i.imgur.com/YNC1nWO.png).

However, apps like Thunar and Gnome Disk Utility works perfectly fine as seen [here](https://i.imgur.com/cz9V8mt.png), so it seems like something happened with the GTK2 part of the theme.

**Comment by Fausto-Korpsvart** [comment]
> 

Yes, thanks for reporting, in the next few days I will make an update and fix the GTK2 issue.

**Comment by rafay99-epic** [comment]
# Solution:
I have seen this before. When I am using Awesome Window Manager, sometimes Thunar does not work completely. There is a simple fix for this. In the themes, there is a folder called gtk2.0, gtk3.0, and gtk.40. Just copy those folders to the $HOME/.config folder, then use LXAppearance or any other themeing to set the theme.

**Note:** If you are using LXAppearance, then you might need to reboot your system. After that, no problem.

## Reason for this Problem.
You see, with gnome 40, there is a move from GTK3 to GTK4, but some of the components are GTK2, some are GTK3, and some are GTK4, so it will take some time to move completely to GTK4.
