### ISSUE TITLE
Can you release .scss files?

### ISSUE THREAD

**Issue by mrvruj** [Fausto-Korpsvart/Tokyo-Night-GTK-Theme#27]
Hi! I love your theme but I wanted to make some color modifications... is it possible for you to share the .scss files you use to build these themes so I can edit the colors directly? Thanks.

**Comment by Fausto-Korpsvart** [comment]
> Hi! I love your theme but I wanted to make some color modifications... is it possible for you to share the .scss files you use to build these themes so I can edit the colors directly? Thanks.

Sorry, I am not using any framework at the moment, maybe in the future I will start using one.
