### ISSUE TITLE
Maximise/Minimise icons aren't visible in gnome 43

### ISSUE THREAD

**Issue by xtanion** [Fausto-Korpsvart/Tokyo-Night-GTK-Theme#28]
![image](https://user-images.githubusercontent.com/74976752/209081064-e50f8993-7eb5-4cd7-99e3-38f5ff2a6c80.png)

I'm using Ubuntu `22.10` (gnome 43).

**Comment by Fausto-Korpsvart** [comment]
> ![image](https://user-images.githubusercontent.com/74976752/209081064-e50f8993-7eb5-4cd7-99e3-38f5ff2a6c80.png)
> 
> I'm using Ubuntu `22.10` (gnome 43).

That's very strange, I'm going to check again, because I check every theme on several distros and I haven't seen that error so far.

Thanks for reporting it.

**Comment by rafay99-epic** [comment]
> ![image](https://user-images.githubusercontent.com/74976752/209081064-e50f8993-7eb5-4cd7-99e3-38f5ff2a6c80.png)
> 
> I'm using Ubuntu `22.10` (gnome 43).


Brother, Have you enabled the max and min buttons from the Gnome Tweaks application? By default, they are disabled; maybe by enabling them, this issue can be resolved, because I have not faced any issues like this.
