### ISSUE TITLE
How to use icon pack

### ISSUE THREAD

**Issue by pavanjoshi914** [Fausto-Korpsvart/Tokyo-Night-GTK-Theme#29]
I have installed tokyo night theme but tweaks is unable to detect icon pack. steps to install icon pack in tokyo night?

![Screenshot from 2022-12-26 20-40-58](https://user-images.githubusercontent.com/55848322/209562364-d9fd7b32-dc3d-4d71-a0ab-2f8e991e513b.png)

**Comment by Fausto-Korpsvart** [comment]
> I have installed tokyo night theme but tweaks is unable to detect icon pack. steps to install icon pack in tokyo night?
> 
> ![Screenshot from 2022-12-26 20-40-58](https://user-images.githubusercontent.com/55848322/209562364-d9fd7b32-dc3d-4d71-a0ab-2f8e991e513b.png)

Hello, @pavanjoshi914 

How have you installed the icons?
The icons should be placed in the following paths: `~/.icons` or in `~/.local/share/icons`, usually the first path is the most used; if you have already placed the icons theme folder inside `~/.icons`, `Tweaks` should detect the package, you can try closing and opening `Tweaks` or check that inside the icons directory are the different icons folders and the `index.theme` file.
