### ISSUE TITLE
Gnome Terminal: Emphasizing the active tab (e.g. when switching tabs)

### ISSUE THREAD

**Issue by GyrosKomplett** [Fausto-Korpsvart/Tokyo-Night-GTK-Theme#3]
Very nice theme, my favourite on gnome-look.org.
I've got a feature request, though.
When using the gnome terminal, I find it hard to recognize the active console tab. Even when switching the tabs, there is very little change in the appearance of the active tab, bringing some confusion into the arrangement of my open tabs.
It would be great if you could highlight that a bit more. Some themes are using a small coloured bar on the bottom side of the tab, maybe this would be a way to go.

Greetings
Tom

![Bildschirmfoto von 2022-02-14 01-01-36](https://user-images.githubusercontent.com/99622743/153781388-d9bb1886-810b-490d-b3a4-fd9a4486c7b1.jpg)

**Comment by Fausto-Korpsvart** [comment]
> Very nice theme, my favourite on gnome-look.org. I've got a feature request, though. When using the gnome terminal, I find it hard to recognize the active console tab. Even when switching the tabs, there is very little change in the appearance of the active tab, bringing some confusion into the arrangement of my open tabs. It would be great if you could highlight that a bit more. Some themes are using a small coloured bar on the bottom side of the tab, maybe this would be a way to go.
> 
> Greetings Tom
> 
> ![Bildschirmfoto von 2022-02-14 01-01-36](https://user-images.githubusercontent.com/99622743/153781388-d9bb1886-810b-490d-b3a4-fd9a4486c7b1.jpg)

You're right, I hadn't noticed because I use Tmux; but I'll update soon to fix the problem, thanks for reporting.
