### ISSUE TITLE
Can't find Theme-Name-BL-GS themes

### ISSUE THREAD

**Issue by jareer12** [Fausto-Korpsvart/Tokyo-Night-GTK-Theme#30]
The border-less theme does not exist on the Github repository or [GnomeLook](https://www.gnome-look.org/p/1681315/)

**Comment by Fausto-Korpsvart** [comment]
> The border-less theme does not exist on the Github repository or [GnomeLook](https://www.gnome-look.org/p/1681315/)

[On Pling](https://www.pling.com/p/1681470)
And in the repo it is inside the themes folder.
GS = Gnome Shell ... that means it's only the theme for the Shell.

**Comment by jareer12** [comment]
Thanks!
