### ISSUE TITLE
wallpaper Request

### ISSUE THREAD

**Issue by rafay99-epic** [Fausto-Korpsvart/Tokyo-Night-GTK-Theme#31]
# Request:
I remember in the previous version of the application there were some wallpapers, and now they are not available. I love this theme, so can you provide those wallpapers to complete my desktop environment?

**Comment by atraxsrc** [comment]
Hi, I saved some in thi repo last year, not sure if you taste https://github.com/atraxsrc/wallpapers

**Comment by rafay99-epic** [comment]
Thank brother, You are the best.

**Comment by rafay99-epic** [comment]
> 

it's alright, I can understand, thank you for making and maintaining this awesome theme. I love it.
