### ISSUE TITLE
System Menu look

### ISSUE THREAD

**Issue by TonyKatana95** [Fausto-Korpsvart/Tokyo-Night-GTK-Theme#34]
Hi! Using GNOME 44. Don't remember for sure, but that thing could be with previous GNOME release too. I believe there is a way to fix it, but I still haven't find it yet. Could editing gnome-shell.css help?

![without_theme](https://user-images.githubusercontent.com/77319703/233796358-ac0d9d49-aaa7-49f1-8632-9bad4467bf34.png)

![with_theme](https://user-images.githubusercontent.com/77319703/233796360-fe57485f-b1bb-4e88-8fd3-b3b6c3ed4768.png)

**Comment by Fausto-Korpsvart** [comment]
> Hi! Using GNOME 44. Don't remember for sure, but that thing could be with previous GNOME release too. I believe there is a way to fix it, but I still haven't find it yet. Could editing gnome-shell.css help?
> 
> ![without_theme](https://user-images.githubusercontent.com/77319703/233796358-ac0d9d49-aaa7-49f1-8632-9bad4467bf34.png)
> 
> ![with_theme](https://user-images.githubusercontent.com/77319703/233796360-fe57485f-b1bb-4e88-8fd3-b3b6c3ed4768.png)

Thanks for reporting.

I hope to have some time soon to fix bugs and update every theme, work doesn't leave me much time for now, so when I have a moment I'll dedicate myself to fixing bugs and update.

Thanks for your support.
