### ISSUE TITLE
Compatibility with GNOME 44

### ISSUE THREAD

**Issue by D3vil0p3r** [Fausto-Korpsvart/Tokyo-Night-GTK-Theme#35]
Is this theme (and other theme you created) compatible with the new GNOME 44?

**Comment by SteinGaming** [comment]
> Is this theme (and other theme you created) compatible with the new GNOME 44?

@D3vil0p3r doesn't seem like it does, tried `Tokyonight-Strom-BL` which causes broken shadows outside of the window

**Comment by D3vil0p3r** [comment]
Yes, just look my window:
![image](https://github.com/Fausto-Korpsvart/Tokyo-Night-GTK-Theme/assets/83867734/bfed6e67-ffb6-4870-b98c-6c21e0a62181)

**Comment by Skydeke** [comment]
Pretty sure this is related to https://gitlab.gnome.org/GNOME/gtk/-/merge_requests/5857

**Comment by Fausto-Korpsvart** [comment]
> Yes, just look my window: ![image](https://user-images.githubusercontent.com/83867734/237212970-bfed6e67-ffb6-4870-b98c-6c21e0a62181.png)

Greetings all.

This problem does not seem to be theme related, as far as I have investigated, the problem is with `Mutter`.
Even the theme I based it on, `Graphite` seems to have the same problems, it's not lack of support for `Gnome 44`, the problem is with `Mutter` and related to the way it renders elements.

[Here](https://gitlab.gnome.org/GNOME/mutter/-/issues/2725) the origin of the problem seems to be better explained.

[Here](https://github.com/vinceliuice/Colloid-gtk-theme/issues/113#issuecomment-1531146340) is the temporary solution offered by @vinceliuice

Thank you for reporting and for your support, I know I have not been very active in the project lately, but it is due to my work that I have not had much time, I will soon make an update to fix the problems with `Gnome Shell` that many have reported.

I appreciate your patience and support.

**Comment by D3vil0p3r** [comment]
Thank you for the answer @Fausto-Korpsvart 

I read the temporary solution but it does not work (in Xorg). I tested it on your Tokyo Night theme:
![image](https://github.com/Fausto-Korpsvart/Tokyo-Night-GTK-Theme/assets/83867734/365d751d-4cbb-408f-9a0b-59dbda8fae0e)

I tested also the Graphite theme of @vinceliuice and it works correctly also without that temporary fix:
![image](https://github.com/Fausto-Korpsvart/Tokyo-Night-GTK-Theme/assets/83867734/f3e45afb-3a03-4805-8112-33271d20baa1)

**Comment by Fausto-Korpsvart** [comment]
> Thank you for the answer @Fausto-Korpsvart
> 
> I applied the temporary solution but it does not work (in Xorg). I tested it on your Tokyo Night theme: ![image](https://user-images.githubusercontent.com/83867734/237488461-365d751d-4cbb-408f-9a0b-59dbda8fae0e.png)
> 
> I tested also the Graphite theme of @vinceliuice and it works correctly also without that temporary fix: ![image](https://user-images.githubusercontent.com/83867734/237489135-f3e45afb-3a03-4805-8112-33271d20baa1.png)

I have already updated the `Graphite` repository, and I am working on the new theme update, I am checking and there seems to be no errors.
I hope to be able to do the Tokyonight update next week.

Gnome Terminal
![gnome-terminal](https://github.com/Fausto-Korpsvart/Tokyo-Night-GTK-Theme/assets/47998118/970a0e66-db6d-4e35-beb4-89e35252cc57)

**Comment by D3vil0p3r** [comment]
@Fausto-Korpsvart thank you man. The new updates will come also for other your themes (i.e., [Gruvbox](https://github.com/Fausto-Korpsvart/Gruvbox-GTK-Theme))?

**Comment by Fausto-Korpsvart** [comment]
> @Fausto-Korpsvart thank you man. The new updates will come also for other your themes (i.e., [Gruvbox](https://github.com/Fausto-Korpsvart/Gruvbox-GTK-Theme))?

@D3vil0p3r, yes, for all themes.

**Comment by Fausto-Korpsvart** [comment]
Tokyonight is now up to date, I would appreciate reports to see if there are still bugs to fix.

**Comment by D3vil0p3r** [comment]
I'm currently abroad but I will try to get any random computer on my sight for testing it. I will trst Tokyo Night and Gruvbox.

**Comment by D3vil0p3r** [comment]
@Fausto-Korpsvart I tested the latest commit files both for Tokyo Night and Gruvbox themes, but I'm still getting the same issue. Here the example on Tokyo Night theme:
![image](https://github.com/Fausto-Korpsvart/Tokyo-Night-GTK-Theme/assets/83867734/1ea5a924-fe53-4e31-a14d-f4f1bc8bf3c1)

I'm using an Arch-based distro with GNOME 44.1 Xorg and the Tokyo Night commit I'm using is the latest one (53.a25fd5e8). For Gruvbox is the latest one too (50.c7a85272).

**Comment by Fausto-Korpsvart** [comment]
> @Fausto-Korpsvart I tested the latest commit files both for Tokyo Night and Gruvbox themes, but I'm still getting the same issue. Here the example on Tokyo Night theme:
> 
> [Kitty](https://github.com/kovidgoyal/kitty) terminal: ![image](https://user-images.githubusercontent.com/83867734/239472155-1ea5a924-fe53-4e31-a14d-f4f1bc8bf3c1.png)
> 
> I'm using an Arch-based distro with GNOME 44.1 Xorg and the Tokyo Night commit I'm using is the latest one (53.a25fd5e8). For Gruvbox is the latest one too (50.c7a85272).
> 
> By GNOME Terminal it works correctly. I don't have that issue. I'm noting that it occurs mainly for those windows developed by Python GTK (indeed Kitty terminal is developed by Python). Indeed if I open some GTK windows developed by Python, I get the following behavior: ![image](https://user-images.githubusercontent.com/83867734/239474811-b1dd0ca2-84cc-49eb-81b9-885f131b2540.png)

That's quite strange, I don't understand the source of the problem, the theme I use as template is `Graphite` and I have updated to its latest version.

What Arch based distribution are you using? Because I test on different distros and I haven't seen this problem, in fact I use `Kitty` and I haven't seen this problem after the update.

I want to test on the distro you are using with Xorg to find the source and fix the bug.
Here is a screenshot of kitty with Tokyonight Borderless version on Wayland
![kitty](https://github.com/Fausto-Korpsvart/Tokyo-Night-GTK-Theme/assets/47998118/e0193aee-35eb-449a-99a9-9aa5116a065c)

**Comment by Fausto-Korpsvart** [comment]
Updated.
Please check and report if the error persists }:-]

**Comment by Fausto-Korpsvart** [comment]
> Thank you for the answer @Fausto-Korpsvart
> 
> The distro I'm using is [Athena OS](https://github.com/Athena-OS/athena-iso) that is a pentesting OS Arch-based I made for Cyber Security professionals that use some of your themes. I invite you to download the ISO of the beta version that will be released in the next days and that has this issue (since it is based on GNOME 44): https://www.dropbox.com/s/dlf9klsujzzyj6e/athena-2023.05.15-x86_64.iso?dl=0
> 
> Assign to it at least 4 GB RAM, 20 or 30 GB of disk space and 2 cores. When the Live ISO will run, a window appears, click "Online Installer" and on "Themes" section, select BlueEyesSamurai (Tokyo Night based) or CyborgGruvbox (Gruvbox GTK based).
> 
> If you would like to keep a closer contact with me, you can reach me on Athena OS Discord server: https://discord.gg/DNjvQkb5Ad

@D3vil0p3r, Interesting, I'll have a look.
For my attempts to learn some cybersecurity I've been using Fedora Security Lab, I've tried the classics before, Kali and Parrot, so far I haven't tried Black Arch based, sounds very interesting, I'll check it out, thanks }:-]

**Comment by JoZ3** [comment]
> Updated. Please check and report if the error persists }:-]

thanks mate :), tested with Gruvbox and Tokyo-Night and works fine,  with Kanagawa the issue continue.

**Comment by Fausto-Korpsvart** [comment]
> > Updated. Please check and report if the error persists }:-]
> 
> thanks mate :), tested with Gruvbox and Tokyo-Night and works fine, with Kanagawa the issue continue.

I haven't updated Kanagawa yet, it will be next along with Nightfox }:-]

**Comment by D3vil0p3r** [comment]
@Fausto-Korpsvart thank you. I'm testing theme and it seems Tokyo Night and Gruvbox themes are working correctly now also on Athena OS and Xorg. Just one note for Gruvbox: on "themes" folder the names of subfolders contain typo "Grubvox" instead of "Gruvbox":
![image](https://github.com/Fausto-Korpsvart/Tokyo-Night-GTK-Theme/assets/83867734/b357252d-19b2-49e9-81d2-e46d70e7e6ba)

**Comment by JoZ3** [comment]
> @Fausto-Korpsvart thank you. I'm testing theme and it seems Tokyo Night and Gruvbox themes are working correctly now also on Athena OS and Xorg. Just one note for Gruvbox: on "themes" folder the names of subfolders contain typo "Grubvox" instead of "Gruvbox": ![image](https://user-images.githubusercontent.com/83867734/239639385-b357252d-19b2-49e9-81d2-e46d70e7e6ba.png)

haha,  hadn't noticed that detail :)
![imagen](https://github.com/Fausto-Korpsvart/Tokyo-Night-GTK-Theme/assets/87251078/b8676454-8d4b-470d-8a70-b7dd206c84ab)

**Comment by Fausto-Korpsvart** [comment]
> @Fausto-Korpsvart thank you. I'm testing theme and it seems Tokyo Night and Gruvbox themes are working correctly now also on Athena OS and Xorg. Just one note for Gruvbox: on "themes" folder the names of subfolders contain typo "Grubvox" instead of "Gruvbox": ![image](https://user-images.githubusercontent.com/83867734/239639385-b357252d-19b2-49e9-81d2-e46d70e7e6ba.png)

Yeah, sorry, I really knew I had spelt it wrong and with the bug fixes I completely forgot to change the name, I only realised minutes after I had done the update xD
I will change the name when I upload the `Gruvbox Medium` Theme in the next few days.

Thanks for reporting }:-]

**Comment by D3vil0p3r** [comment]
Is it correct I have these blue and green colors in Gruvbox theme?
![image](https://github.com/Fausto-Korpsvart/Tokyo-Night-GTK-Theme/assets/83867734/eb42548d-1b64-4c83-acd5-ce8211d54658)

![image](https://github.com/Fausto-Korpsvart/Tokyo-Night-GTK-Theme/assets/83867734/7e24b25e-ec19-40d5-9a41-360d6e3f620f)

**Comment by Fausto-Korpsvart** [comment]
> > Updated. Please check and report if the error persists }:-]
> 
> thanks mate :), tested with Gruvbox and Tokyo-Night and works fine, with Kanagawa the issue continue.

`Kanagawa` theme updated, @JoZ3.

**Comment by D3vil0p3r** [comment]
I see also the colors of Gruvbox theme have been fixed. Thank you. I think this issue can be closed. I will follow the issue I opened yesterday about Nightfox theme at https://github.com/Fausto-Korpsvart/Nightfox-GTK-Theme/issues/3

**Comment by Fausto-Korpsvart** [comment]
> I see also the colors of Gruvbox theme have been fixed. Thank you. I think this issue can be closed. I will follow the issue I opened yesterday about Nightfox theme at [Fausto-Korpsvart/Nightfox-GTK-Theme#3](https://github.com/Fausto-Korpsvart/Nightfox-GTK-Theme/issues/3)

Yes, the `Nightfox` theme will be updated tomorrow or in the next few days, as I have a busy day tomorrow and I hope to dedicate some time to update and upload it, but it is the next theme to be updated.

Thanks for your support }:-]

**Comment by D3vil0p3r** [comment]
Hey @Fausto-Korpsvart can you try to please open a GTK window with Tokyo Night theme and then press on the keyboard `ALT + Print` keys? Usually this key combo is used for getting the screenshot of the active window.

What I note is that, if you do that, it saves the screenshot of the active window but the saved image keeps a transparent border, for example:
<img width="702" alt="image" src="https://github.com/Fausto-Korpsvart/Tokyo-Night-GTK-Theme/assets/83867734/9485a10f-30ca-41f2-81b4-0e63170ff7bc">

The problem with that is: when a user takes a screenshot of the active window and it copies and pastes the image somewhere (for example in a document), the image will appear a little smaller than the original one, so the user is forced to remove manually (i.e., by Photoshop) this transparent border.

**Comment by Fausto-Korpsvart** [comment]
> Hey @Fausto-Korpsvart can you try to please open a GTK window with Tokyo Night theme and then press on the keyboard `ALT + Print` keys? Usually this key combo is used for getting the screenshot of the active window.
> 
> What I note is that, if you do that, it saves the screenshot of the active window but the saved image keeps a transparent border, for example: <img alt="image" width="702" src="https://user-images.githubusercontent.com/83867734/253346063-9485a10f-30ca-41f2-81b4-0e63170ff7bc.png">
> 
> The problem with that is: when a user takes a screenshot of the active window and it copies and pastes the image somewhere (for example in a document), the image will appear a little smaller than the original one, so the user is forced to remove manually (i.e., by Photoshop) this transparent border.
> 
> I think it is related to the famous outer shadow around the windows we had at the beginning as issue, and now that is reduced to 0, something invisible should be remained there.

Greetings, @D3vil0p3r.

Yes, I know what you're talking about, when I made the presentation image of the themes I ran into this problem and had to edit some images to remove that border, and that's extra work.

I am currently working on many improvements, one of them is the change of base theme, I plan to change to the `Jasper` theme from the same author of `Graphite,` I am testing and changing things in the source code to generate the themes from the `scss` sheets.
Because of work I can't keep track of each theme separately by editing each theme from the `css` sheets, so it's time to automate this work a bit to support and update more often.

I plan to make the necessary changes to keep the current styling, but leave many others as default, this includes the shadows and borders of the borderless themes.

So, give me some time, I hope to finish all this in this week, work permitting, and do the necessary tests to update this theme as soon as possible.

Thanks for your support

**Comment by D3vil0p3r** [comment]
Thank you. If there are some tasks we could be useful, please tell us.
