### ISSUE TITLE
New update is great but something is missing 

### ISSUE THREAD

**Issue by NeuronSooup** [Fausto-Korpsvart/Tokyo-Night-GTK-Theme#4]
How it should look like: https://ibb.co/1LyZC7N
The new update: https://ibb.co/dJwRjDT

**Comment by Fausto-Korpsvart** [comment]
> How it should look like: https://ibb.co/1LyZC7N The new update: https://ibb.co/dJwRjDT

Sorry for taking so long to respond, @NeuronSooup, tough week at work.
And yes, I realised later that I forgot that little detail, in the other issues I have not put it and I forgot it in this update; I will include it in the next update this week, thank you.

**Comment by Icy-Thought** [comment]
@Fausto-Korpsvart Is there any chance that you could create variants based around the older look? 
I liked the previous selection borders!

**Comment by Fausto-Korpsvart** [comment]
> @Fausto-Korpsvart Is there any chance that you could create variants based around the older look? I liked the previous selection borders!


Do you mean the colour of the active window border like the Strom version?

**Comment by Icy-Thought** [comment]
> Do you mean the colour of the active window border like the Strom version?

Don't know what verson it was available in, but I was referring to the orange (red?) marker for "current directory" in the first screenshot.

**Comment by Fausto-Korpsvart** [comment]
> 



> > Do you mean the colour of the active window border like the Strom version?
> 
> Don't know what verson it was available in, but I was referring to the orange (red?) marker for "current directory" in the first screenshot.

I understand, of course, in the next update I will remember to make this change.

Thank you for your support.

**Comment by Icy-Thought** [comment]
Appreciate it :blush:
