### ISSUE TITLE
Godot (Bottom-left corner and Bottom-Right corner are buggy)

### ISSUE THREAD

**Issue by RosGtHub** [Fausto-Korpsvart/Tokyo-Night-GTK-Theme#40]
This is the issue: 
![Screenshot from 2023-08-05 20-32-01](https://github.com/Fausto-Korpsvart/Tokyo-Night-GTK-Theme/assets/89165766/0f0a632b-b230-49a5-b0cc-5a44f172b2eb)
Hope you can help me, thanks you in advance! (i think is a problem of the application, but i'm not an expert)

**Comment by Fausto-Korpsvart** [comment]
> This is the issue: ![Screenshot from 2023-08-05 20-32-01](https://user-images.githubusercontent.com/89165766/258602396-0f0a632b-b230-49a5-b0cc-5a44f172b2eb.png) Hope you can help me, thanks you in advance! (i think is a problem of the application, but i'm not an expert)

Sorry for the delay.

Thanks for reporting, I will check and fix as soon as possible.

**Comment by RosGtHub** [comment]
alright
