### ISSUE TITLE
GNOME nautilus titlebar

### ISSUE THREAD

**Issue by 0x1F8F** [Fausto-Korpsvart/Tokyo-Night-GTK-Theme#41]
When using a titlebar button on the left side, it increases the padding of the titlebar.

GNOME nautilus 44.2.1

**Comment by Fausto-Korpsvart** [comment]
> When using a titlebar button on the left side, it increases the padding of the titlebar.
> 
> GNOME nautilus 44.2.1

Thanks for the report, I will check to fix and update as soon as possible.
