### ISSUE TITLE
How to change status bar text color

### ISSUE THREAD

**Issue by AlekDG** [Fausto-Korpsvart/Tokyo-Night-GTK-Theme#44]
Hi, I'm stupid and, in the cinnamon .css file, I can't figure out which block corresponds to the text and icons on the status bar
It looks nice but I find it hard to read during daytime so I would like to just make it white
[How it looks currently:](https://imgur.com/a/Zd6C6q1)

**Comment by Fausto-Korpsvart** [comment]
> Hi, I'm stupid and, in the cinnamon .css file, I can't figure out which block corresponds to the text and icons on the status bar It looks nice but I find it hard to read during daytime so I would like to just make it white [How it looks currently:](https://imgur.com/a/Zd6C6q1)

You need to search on the panel, if I remember correctly, I don't have the code at hand right now, but it is the panel that has this font colour setting.

**Comment by AlekDG** [comment]
> You need to search on the panel, if I remember correctly, I don't have the code at hand right now, but it is the panel that has this font colour setting.
Thank you for your reply
Unfortunately, I tried going through everything that had the word "panel" in the title with a color parameter and no luck
I'm no hurry so I seriously don't mind waiting for you to have a look quick at the code and telling me, if that's an option.
