### ISSUE TITLE
Nemo left sidebar

### ISSUE THREAD

**Issue by krstfz** [Fausto-Korpsvart/Tokyo-Night-GTK-Theme#45]
Hey! 

I've noticed that the theme looks weird whilst using Nemo file manager. In the original Graphite theme this is fixed by applying the "normal" tweak during install. Can I fix it somehow and if so do you know where? I'm not really that skilled in css so I have no idea where to look. 
Thanks for your hard work!

![image](https://github.com/Fausto-Korpsvart/Tokyo-Night-GTK-Theme/assets/126676125/a02152cd-9773-4f13-9b61-2a4908c88ec7)

**Comment by Fausto-Korpsvart** [comment]
> Hey!
> 
> I've noticed that the theme looks weird whilst using Nemo file manager. In the original Graphite theme this is fixed by applying the "normal" tweak during install. Can I fix it somehow and if so do you know where? I'm not really that skilled in css so I have no idea where to look. Thanks for your hard work!
> 
> ![image](https://user-images.githubusercontent.com/126676125/272044774-a02152cd-9773-4f13-9b61-2a4908c88ec7.png)

Thanks for reporting, @krstfz.

Currently, I'm working on the new update, this one brings Jasper as a new base theme, so I'm going to check the Nemo styles in Jasper to adapt them in the best way to the Tokyonight theme.

So as soon as I finish all the changes and work allows me, I will make the update.

**Comment by krstfz** [comment]
Awesome! Thanks for the quick response and best of luck.
