### ISSUE TITLE
Xfce 4.16 Window Manager theme is the only thing that don't work

### ISSUE THREAD

**Issue by cromeoli** [Fausto-Korpsvart/Tokyo-Night-GTK-Theme#46]
I have installed this theme on Xfce 4.16 and the only issue is that the window manager is not appearing, is there any fix for this?

**Comment by Fausto-Korpsvart** [comment]
> I have installed this theme on Xfce 4.16 and the only issue is that the window manager is not appearing, is there any fix for this?

I don't quite understand what you mean,
could you be a bit more specific?

Anyway, I'll do some updating soon, as I have some free time at work, I'm dedicating time to this project to update as soon as possible.

Thanks for reporting.

**Comment by cromeoli** [comment]
Sorry for expressing it in such an ambiguous way. I meant that I can apply the theme from the "appearance" menu without any problem and it does apply (apparently) the styles where it should apply them. 

In xfce 4.16 I must apply the styles of the window frames (the frame that contains the controls to close, maximize or minimize a window) in a separate menu. When I do this it seems that the window frames do not appear, and I have tried applying other themes to see if it was just this particular theme and indeed it seems that it is. 

However, in some applications like google chrome or firefox the window border does appear. 

Anyway I have made this video so that you can see more clearly what I mean:

https://github.com/Fausto-Korpsvart/Tokyo-Night-GTK-Theme/assets/92324278/837731dd-b736-455f-b89b-ce0cff907c87

And also a screenshot of google chrome window frame in comparison of console or thunar window frame with the theme applied:

![image](https://github.com/Fausto-Korpsvart/Tokyo-Night-GTK-Theme/assets/92324278/b8ef5031-ff47-4526-8fbe-750bbb7d5a32)

Thank you very much for your work, the finish of the theme seems to me excellent and the quality is noticeable, soon I hope at least to be able to make a donation to pay you a breakfast at least!

**Comment by Fausto-Korpsvart** [comment]
Thanks, to be honest, I don't understand where the error can come from, maybe XCFE has updated, and the theme has to be adapted to these changes, I don't know, but thanks for the report, I will check well before the new update to avoid this error.

**Comment by meymigrou** [comment]
Hello! I can report the same problem in the latest Manjaro Gnome version. Just made a fresh installation and moved to install Tokyo Night and there's lots of places I don't see the theme, including the File Manager, Add/Remove Software, Terminal, etc.

Any solution?
