### ISSUE TITLE
Incorrect Sidebar Color in GTK4 Applications

### ISSUE THREAD

**Issue by uosyph** [Fausto-Korpsvart/Tokyo-Night-GTK-Theme#49]
#### There's an issue with the sidebar color in various GTK4 apps. Initially, I thought it was specific to Nautilus and opened a [pull request](https://github.com/Fausto-Korpsvart/Tokyo-Night-GTK-Theme/pull/48) to address it. However, upon further testing, it seems that the problem extends to all GTK4 applications.

<br>

![nautilus](https://github.com/Fausto-Korpsvart/Tokyo-Night-GTK-Theme/assets/107230184/8f29c338-6e94-4faf-9856-679ab53201fe)

![firefox bookmarks](https://github.com/Fausto-Korpsvart/Tokyo-Night-GTK-Theme/assets/107230184/0446c788-ab7a-483a-bd80-6310789aabe0)

![settings](https://github.com/Fausto-Korpsvart/Tokyo-Night-GTK-Theme/assets/107230184/70ff1ebb-a0b3-429c-9f85-0b56fb22f9ac)

![characters](https://github.com/Fausto-Korpsvart/Tokyo-Night-GTK-Theme/assets/107230184/98ecbf14-1b8f-4296-95c7-7a597fbc6ab9)

**Comment by eldskald** [comment]
Is this Gnome 45? It's not supported yet.

**Comment by yousafesaeed** [comment]
Yeah it is, that's why! Thanks for clarifying.

**Comment by Fausto-Korpsvart** [comment]
I am sorry for the delay in replying and updating, but due to family issues I have not been able to be very active in the project.

I have already solved this problem and it is currently working in Gnome 45, but I haven't done the update yet because I want to fix small details that, as I said, due to some family issues I haven't had the time to solve. 

This is a screenshot of how this problem is already solved.

I want to dedicate this week to fix small bugs in GNOME and XFCE, I also want to check the other desktops so I can update and make everything work properly.

Sorry this is taking so long and thanks for your understanding and patience.

![TN-Testing](https://github.com/Fausto-Korpsvart/Tokyo-Night-GTK-Theme/assets/47998118/6de73588-2ce0-4814-bcda-408eeff42517)

**Comment by Fausto-Korpsvart** [comment]
Here is a link for you to test some versions of the theme, you can see and test the theme and tell me if something is wrong, I don't want to update the source code yet so when I upload it some bugs are fixed, for that reason I share this link, I hope you like the progress and any problem you see let me know to fix bugs.

[Tokyonight-Testing](https://github.com/Fausto-Korpsvart/Tokyo-Night-GTK-Theme/files/13716874/Tokyonight-Testing.zip)

**Comment by yousafesaeed** [comment]
I'm sorry to hear about your family issues, I hope things get easier for you soon. I appreciate your update and understand that personal matters take precedence.

I'll check out the test version in the next couple of days and give you a heads up if anything seems off.

Thanks a bunch for your work, take care!

**Comment by smokingsnakes83** [comment]
> Here is a link for you to test some versions of the theme, you can see and test the theme and tell me if something is wrong, I don't want to update the source code yet so when I upload it some bugs are fixed, for that reason I share this link, I hope you like the progress and any problem you see let me know to fix bugs.
> 
> [Tokyonight-Testing](https://github.com/Fausto-Korpsvart/Tokyo-Night-GTK-Theme/files/13716874/Tokyonight-Testing.zip)

Awesome, TKS!

**Comment by eldskald** [comment]
![image](https://github.com/Fausto-Korpsvart/Tokyo-Night-GTK-Theme/assets/49042948/1147954e-b9b5-4b03-9259-bac7f8f0065e)

![image](https://github.com/Fausto-Korpsvart/Tokyo-Night-GTK-Theme/assets/49042948/0fbeb12f-6b5b-4ed7-87a6-3a1d813f9fae)

That first picture is the bottom of a kitty terminal, the second is the bottom of Gnome's settings. You can see that kitty has weird corners, it's like its borders have a corner radius but the contents of the window doesn't while the other app's corners are just normally rounded.

Kitty seems unaffected by the settings on Gnome Tweaks, so I'm assuming it's GTK 4.0, unlike every other application I saw that has normal rounded corners and were affected by these settings. I tried alacritty and it has the same issue, don't know other apps that use these files we put on the 4.0 folder but it's worth looking into them.
