### ISSUE TITLE
Launcher in the screenshot. 

### ISSUE THREAD

**Issue by Nakamerica** [Fausto-Korpsvart/Tokyo-Night-GTK-Theme#5]
Hi, what launcher are you using in the screenshot? Thanks.

**Comment by Fausto-Korpsvart** [comment]
Sorry for taking so long to respond, @Nakamerica, tough week at work.
The launcher is 'Ulauncher', here are the themes: https://www.pling.com/p/1681817/

**Comment by Nakamerica** [comment]
That is completely understandable, no problems. Thanks for getting back.
