### ISSUE TITLE
index.theme uses "fixed" instead of "Fixed" for icon type of stock/x icons

### ISSUE THREAD

**Issue by ava5627** [Fausto-Korpsvart/Tokyo-Night-GTK-Theme#50]
```
[stock/16]
Size=16
Context=Stock
Type=fixed
```
instead of
```
[stock/16]
Size=16
Context=Stock
Type=Fixed
```

**Comment by Fausto-Korpsvart** [comment]
> ```
> [stock/16]
> Size=16
> Context=Stock
> Type=fixed
> ```
> 
> instead of
> 
> ```
> [stock/16]
> Size=16
> Context=Stock
> Type=Fixed
> ```

Thanks for reporting it, I'll take a look and update later.
