### ISSUE TITLE
Weird looking file picker in VS Code

### ISSUE THREAD

**Issue by alan-delgado** [Fausto-Korpsvart/Tokyo-Night-GTK-Theme#52]
I recently updated to the latest version of the Tokyonight-Dark theme, loving the update! But I found an issue when I try to open a file or select a folder in Visual Studio Code (version 1.87.2), the file picker looks weird, the sidebar's background looks like it's from the Tokyonight-Light theme and the "Open" button looks unthemed. Im using Fedora 39

![Screenshot from 2024-03-21 20-35-05](https://github.com/Fausto-Korpsvart/Tokyo-Night-GTK-Theme/assets/102810539/2f85899c-7fe8-4eb3-900c-913be94c67ca)

**Comment by Fausto-Korpsvart** [comment]
> I recently updated to the latest version of the Tokyonight-Dark theme, loving the update! But I found an issue when I try to open a file or select a folder in Visual Studio Code (version 1.87.2), the file picker looks weird, the sidebar's background looks like it's from the Tokyonight-Light theme and the "Open" button looks unthemed. Im using Fedora 39
> 
> ![Screenshot from 2024-03-21 20-35-05](https://private-user-images.githubusercontent.com/102810539/316052199-2f85899c-7fe8-4eb3-900c-913be94c67ca.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTExMjcwOTQsIm5iZiI6MTcxMTEyNjc5NCwicGF0aCI6Ii8xMDI4MTA1MzkvMzE2MDUyMTk5LTJmODU4OTljLTdmZTgtNGViMy05MDBjLTkxM2JlOTRjNjdjYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyMlQxNjU5NTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMjcxNzA2OWU2YTRmNGExOGYxMmEzMTE5ZmY5MzZkMTI3ZjM1YjMyMTg4OGY3NWRmMjZmNmVhM2E0NWI1MDZlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.efJsFe5MApDWnCyg3X44zPDtvV93Ig6aZSToXdl-3LI)

@alan-delgado, Thanks for reporting, as I finish the assets I will continue to improve the overall styles of the theme.

**Comment by alan-delgado** [comment]
Found another small bug. In Settings -> Network -> Network options (click on menu button), the tabs' background is white, so the text is not legible unless you select the tab or hover over it.

![image](https://github.com/Fausto-Korpsvart/Tokyo-Night-GTK-Theme/assets/102810539/104ee6b9-9c25-49bd-8503-f5c01338e822)

**Comment by Fausto-Korpsvart** [comment]
@alan-delgado, I will check and fix it, it will be ready in the next update.

Thanks for reporting.
