### ISSUE TITLE
Missing thumbnail for theme variant

### ISSUE THREAD

**Issue by leaty** [Fausto-Korpsvart/Tokyo-Night-GTK-Theme#54]
Install fails due to seemingly missing thumbnail `thumbnail-Pink-Storm-Dark.png`.

**Comment by Fausto-Korpsvart** [comment]
> Install fails due to seemingly missing thumbnail `thumbnail-Pink-Storm-Dark.png`.

Hello, @leaty.
The thumbnails are ready, in the next update they will be added to avoid this problem.
Thanks for the report.
