### ISSUE TITLE
Pink accent color way harsher than others

### ISSUE THREAD

**Issue by leaty** [Fausto-Korpsvart/Tokyo-Night-GTK-Theme#55]
This might (?) be intentional, however it's in some pretty *drastic* contrast with the other theme variants so it makes me believe this is wrong. Almost *all* text becomes straight up pink.

Now I don't know what the actual color should be (or if this is in fact intentional) but I winged up a color that works for me (dark only) `$pink-dark: #ff8cc4;`.

https://github.com/Fausto-Korpsvart/Tokyo-Night-GTK-Theme/blob/58a04f1d4be7ee498ddaa31aa8bc5716f554aa0c/theme/src/sass/_color-palette-default.scss#L8-L9

https://github.com/Fausto-Korpsvart/Tokyo-Night-GTK-Theme/blob/58a04f1d4be7ee498ddaa31aa8bc5716f554aa0c/theme/src/sass/_color-palette-storm.scss#L8-L9

https://github.com/Fausto-Korpsvart/Tokyo-Night-GTK-Theme/blob/58a04f1d4be7ee498ddaa31aa8bc5716f554aa0c/theme/src/sass/_color-palette-moon.scss#L8-L9

Contrast seen below between pink-dark and purple-dark:
![image](https://github.com/Fausto-Korpsvart/Tokyo-Night-GTK-Theme/assets/4429327/c3027979-f3d6-420b-9031-fc084880245a)
![image](https://github.com/Fausto-Korpsvart/Tokyo-Night-GTK-Theme/assets/4429327/156e9c12-520a-487a-878b-cb1a79357123)

**Comment by Fausto-Korpsvart** [comment]
> This might (?) be intentional, however it's in some pretty _drastic_ contrast with the other theme variants so it makes me believe this is wrong. Almost _all_ text becomes straight up pink.
> 
> Now I don't know what the actual color should be (or if this is in fact intentional) but I winged up a color that works for me (dark only) `$pink-dark: #ff8cc4;`.
> 
> https://github.com/Fausto-Korpsvart/Tokyo-Night-GTK-Theme/blob/58a04f1d4be7ee498ddaa31aa8bc5716f554aa0c/theme/src/sass/_color-palette-default.scss#L8-L9
> 
> https://github.com/Fausto-Korpsvart/Tokyo-Night-GTK-Theme/blob/58a04f1d4be7ee498ddaa31aa8bc5716f554aa0c/theme/src/sass/_color-palette-storm.scss#L8-L9
> 
> https://github.com/Fausto-Korpsvart/Tokyo-Night-GTK-Theme/blob/58a04f1d4be7ee498ddaa31aa8bc5716f554aa0c/theme/src/sass/_color-palette-moon.scss#L8-L9
> 
> Contrast seen below between pink-dark and purple-dark: ![image](https://private-user-images.githubusercontent.com/4429327/318295441-c3027979-f3d6-420b-9031-fc084880245a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5Nzk1NzEsIm5iZiI6MTcxMTk3OTI3MSwicGF0aCI6Ii80NDI5MzI3LzMxODI5NTQ0MS1jMzAyNzk3OS1mM2Q2LTQyMGItOTAzMS1mYzA4NDg4MDI0NWEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MDFUMTM0NzUxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Yjc5MDE2Zjg2NDlhYjIxMTFhZDkwYWYxMjRmYTg2MzFmOTM3YjlmMjQ2YzBmZjJhNjlmMzY0ZmI2ODUwZDZkMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.sKIVE3p9K2_9vDf5cyQVZ2UoWq77KmV4xyNlld-Mz9A) ![image](https://private-user-images.githubusercontent.com/4429327/318295548-156e9c12-520a-487a-878b-cb1a79357123.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5Nzk1NzEsIm5iZiI6MTcxMTk3OTI3MSwicGF0aCI6Ii80NDI5MzI3LzMxODI5NTU0OC0xNTZlOWMxMi01MjBhLTQ4N2EtODc4Yi1jYjFhNzkzNTcxMjMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MDFUMTM0NzUxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODU4ZjdmZjNiYjAyMWQwYWY4NjM5Y2E0ZTNmYWM4MmM2ZjExMzI4NGY4NTM0NzhjMjk5OWM5Mzk4NjY0OWFhMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.7jXsCssOIgMrTh_YaU-aah0xUr6_y9M3pvfATh414Ag)

Hello, @leaty
Yes, I know what you mean, I'm working on fixing this and other small bugs to update as soon as possible.
Thanks for the report.
