### ISSUE TITLE
White background in dark theme for some elements (including treeview)

### ISSUE THREAD

**Issue by datleviet** [Fausto-Korpsvart/Tokyo-Night-GTK-Theme#56]
I'm using the `TokyoNight-Dark-BL` package from [this link](https://www.pling.com/p/1681315/). When I open [nemo](https://github.com/linuxmint/nemo), some certain elements seem to be adopting light theme styles. The left window is when I use `Ctrl + S` on the browser, and the right window is Nemo itself.

![image](https://github.com/Fausto-Korpsvart/Tokyo-Night-GTK-Theme/assets/69759053/0857f095-79a4-41d7-ba2e-e4f72600258f)

I found these lines in `gtk-3.0/gtk-dark.css` and I have already resolved the issue with the right window.

![image](https://github.com/Fausto-Korpsvart/Tokyo-Night-GTK-Theme/assets/69759053/7cf65894-4327-43e7-bda6-9c6fef8efe67)

However, for the left one, I haven't figured out the classnames of these elements. Could someone please help me? Thank you.

**Comment by tris203** [comment]
I also have the same issue

**Comment by datleviet** [comment]
I closed it because it's a duplicate of #52
