### ISSUE TITLE
Nautilus Places Sidebar Issue

### ISSUE THREAD

**Issue by ShawnMcCool** [Fausto-Korpsvart/Tokyo-Night-GTK-Theme#59]
Hi, I appreciate this theme.

![image](https://github.com/Fausto-Korpsvart/Tokyo-Night-GTK-Theme/assets/560749/b88c841a-d523-4307-9de6-2d07a0438b69)

How can I remove the blue border on the left of the nautilus places active button?

**Comment by Fausto-Korpsvart** [comment]
> Hi, I appreciate this theme.
> 
> ![image](https://private-user-images.githubusercontent.com/560749/337878201-b88c841a-d523-4307-9de6-2d07a0438b69.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwMzA5OTUsIm5iZiI6MTcxODAzMDY5NSwicGF0aCI6Ii81NjA3NDkvMzM3ODc4MjAxLWI4OGM4NDFhLWQ1MjMtNDMwNy05ZGU2LTJkMDdhMDQzOGI2OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxMFQxNDQ0NTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ZmFmZGYzMTVlYmEyZDg3NzVlNmQyZjhiMGI0NjEzNzVlOTM0YzY4MjExNzI0NzE1NGUyYWNmNzY4NTg1MzJjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.8A8Yf0FNb1e5Mk2qA7VgaXbYDnGxSXqBEVowYqzLcXw)
> 
> How can I remove the blue border on the left of the nautilus places active button?



> Hi, I appreciate this theme.
> 
> ![image](https://private-user-images.githubusercontent.com/560749/337878201-b88c841a-d523-4307-9de6-2d07a0438b69.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwMzA5OTUsIm5iZiI6MTcxODAzMDY5NSwicGF0aCI6Ii81NjA3NDkvMzM3ODc4MjAxLWI4OGM4NDFhLWQ1MjMtNDMwNy05ZGU2LTJkMDdhMDQzOGI2OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxMFQxNDQ0NTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ZmFmZGYzMTVlYmEyZDg3NzVlNmQyZjhiMGI0NjEzNzVlOTM0YzY4MjExNzI0NzE1NGUyYWNmNzY4NTg1MzJjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.8A8Yf0FNb1e5Mk2qA7VgaXbYDnGxSXqBEVowYqzLcXw)
> 
> How can I remove the blue border on the left of the nautilus places active button?

Hello, @ShawnMcCool.

Wait for the update these days.
In fact, I had already thought that there is no need for this marking, as the colour of the font already stands out very well.

In these days I will make an update of some themes that brings some changes that I think will look very nice.
