### ISSUE TITLE
color difference in outline

### ISSUE THREAD

**Issue by owhami** [Fausto-Korpsvart/Tokyo-Night-GTK-Theme#7]
Hi Faust, I think it would be better if the outline color in gnome-shell (black) is the same as in gtk (blue).
![Screenshot from 2022-03-26 08-11-52](https://user-images.githubusercontent.com/36553432/160216594-053f38db-59b5-4fcb-9846-db31a2b65c94.png) ![Screenshot from 2022-03-26 08-12-11](https://user-images.githubusercontent.com/36553432/160216620-cbbd3b11-cb17-4b13-98a4-ad7de3e7c63f.png)

Like the original Graphite theme, which has the same outline color.
![Screenshot from 2022-03-26 07-53-01](https://user-images.githubusercontent.com/36553432/160216649-fcdb3494-9b82-408a-95ed-9d57637c5a41.png) ![Screenshot from 2022-03-26 07-53-30](https://user-images.githubusercontent.com/36553432/160216655-2d87bc41-fd42-4d55-9d64-f229d169cac8.png)

Sorry to bother you, and thank you for making the Tokyo Night theme, very comfortable for the eyes.

**Comment by Fausto-Korpsvart** [comment]
> [vanillamatcha](/vanillamatcha)

Hi, @vanillamatcha, you are right and I am working on the update to fix some bugs. Thanks for reporting.
