### ISSUE TITLE
The topbar color

### ISSUE THREAD

**Issue by sMx7d** [Fausto-Korpsvart/Tokyo-Night-GTK-Theme#9]
Hi (:

i have tried to edit the topbar color but i didn't know how to done even after some digging in css files ):
soo i want to change it pls and thanks anyway (the entire theme is amazing , well done)

[https://imgur.com/aV9WJ6b](url)

**Comment by sMx7d** [comment]
and the opacity* (i want to change it )

**Comment by Fausto-Korpsvart** [comment]
> Hi (:
> 
> i have tried to edit the topbar color but i didn't know how to done even after some digging in css files ): soo i want to change it pls and thanks anyway (the entire theme is amazing , well done)
> 
> [https://imgur.com/aV9WJ6b](url)

Hi, @sMx7d, I hope this week to have some time to upload the new bugfix update, I'm currently working on fixing bugs that occur with the Gnome 42 update, I also hope to add themes for Cinnamon and XFCE, please be patient, this week I hope to update little by little.

Thanks for reporting and for your support. };-]
